backend:
  name: git-gateway # Prod
  repo: recrea-t/casabernatisil
  branch: main

local_backend: true

media_folder: static/images
public_folder: /images

site_url: https://casabernatisil.netlify.app
display_url: https://casabernatisil.netlify.app
logo_url: https://casabernatisil.netlify.app/images/Logo.png

show_preview_links: false

locale: "ca"

collections:
    #Pages
    - name: 'pages-ca'
      label: 'Pàgines (Català)'
      format: frontmatter
      create: false
      delete: false
      editor:
        preview: false
      files:
        - name: 'inici-ca'
          label: Inici
          file: 'src/pages/index.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Imatge Principal
              name: hero
              widget: object
              collapsed: true
              summary: '{{fields.title}}'
              fields:
                - label: Títol
                  name: title
                  widget: markdown
                - label: Imatge
                  name: image
                  widget: image
                  allow_multiple: false
            - label: Títol Principal
              name: mainTitle
              widget: string
            - label: Descripció Principal
              name: mainDescription
              widget: markdown
            - label: Imatges
              name: images
              widget: list
              allow_add: false
              min: 3
              max: 3
              minimize_collapsed: true
              field: { label: Imatge, name: image, widget: image, allow_multiple: false }
            - label: Títol Raons
              name: whyTitle
              widget: string
            - label: Raons
              name: why
              widget: list
              fields:
                - label: Nom
                  name: name
                  widget: string
                - label: Imatge
                  name: image
                  widget: image
                  allow_multiple: false
            - label: Títol Serveis
              name: servicesTitle
              widget: string
            - label: Raons
              name: services
              widget: list
              allow_add: false
              min: 2
              fields:
                - label: Nom
                  name: name
                  widget: string
                - label: link
                  name: link
                  widget: hidden
                - label: Descripció
                  name: description
                  widget: markdown
                - label: Imatge
                  name: image
                  widget: image
                  allow_multiple: false
        - name: 'casa-ca'
          label: Casa Bernat
          file: 'src/pages/casa-bernat.ca.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Imatge Principal
              name: hero
              widget: object
              summary: '{{fields.title}}'
              fields:
                - label: Títol
                  name: title
                  widget: markdown
                  required: false
                - label: Imatge
                  name: image
                  widget: image
                  allow_multiple: false
            - label: Qui Som
              name: who
              widget: object
              summary: '{{fields.title}}'
              fields:
                - label: Títol
                  name: title
                  widget: string
                - label: Descripció
                  name: description
                  widget: markdown
                - label: Imatge
                  name: image
                  widget: image
                  allow_multiple: false
            - label: Història
              name: history
              widget: object
              summary: '{{fields.title}}'
              fields:
                - label: Títol
                  name: title
                  widget: string
                - label: Descripció
                  name: description
                  widget: markdown
                - label: Imatges
                  name: images
                  widget: list
                  minimize_collapsed: true
                  label_singular: imatge
                  field: { label: Imatge, name: image, widget: image }
            - label: Els Espais
              name: spaces
              widget: object
              summary: '{{fields.title}}'
              fields:
                - label: Títol
                  name: title
                  widget: string
                - label: Descripció
                  name: description
                  widget: markdown
                - label: Imatges
                  name: images
                  widget: list
                  minimize_collapsed: true
                  label_singular: imatge
                  field: { label: Imatge, name: image, widget: image, allow_multiple: false }
